name: moodbot
channels:
  - conda-forge
dependencies:
  - python<=3.11
  - mamba
  - openai
  - numpy
  - pillow
  - opencv
  - pandas
  - scikit-learn
  - ffmpeg
  - pip
  - pip:
    - --index-url https://pypi.org/simple/
    - protobuf>=3.20.3,<4.0.0
    - mcpi
    - mediapipe==0.10.9
    - joblib
    - telepot
    - pillow-heif
    - python-dotenv
